baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Drull'
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "red"
  #change this if I want more item in the navbar
  showMenuItems = 3
  fullWidthTheme = false 
  centerTheme = true 

[languages]
  [languages.en]
    title = "Drull"
    subtitle = "My blog for sharing knowledge"
    keywords = "coding, privacy, FOOS free and open source, hacking"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Drull"
      logoHomeLink = "/"

    [languages.en.menu]
    #add more of these if I want more pages
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
